### PR TITLE
Feature/player movement

### PR DESCRIPTION
**Pull request by Royd54**
This feature is testable by looking at the characters as they move. The interaction animation is testable by interacting with a task and looking at the player with a different client. The same goes for the hit animation. You need to hit a player en look at them with a different client.

### CODE REVIEW

**Review by Stanley-Dam — COMMENTED** [review]
image
This does not seem right xD

**Review by Stanley-Dam — COMMENTED** [review]
image
In `BP_Captain` -> This `SetReplicates` function should be called after the valid check. It is causing nullpointer errors for me.

**Comment by Stanley-Dam** [comment]
I fell through the floor when I walked over a tripwire  and got back up, maybe teleport the player a little higher when they get back up?

**Review by Stanley-Dam — COMMENTED** [review]
Couldn't find anything else, awesome work! :D

**Comment by Royd54** [comment]
> image This does not seem right xD

Removed the captain hat functionality for spawning the placeholder hat.

**Comment by Royd54** [comment]
> image In `BP_Captain` -> This `SetReplicates` function should be called after the valid check. It is causing nullpointer errors for me.

Swapped exec to prevent null pointers

**Comment by Royd54** [comment]
> I fell through the floor when I walked over a tripwire and got back up, maybe teleport the player a little higher when they get back up? (Didn't come up in the tripwire branch review, sorry about that)

Fixed new ragdoll bone positions, to prevent tping trough the floor. This does not happen to me anymore, but should be tested again to make sure.

**Pull request merged**
