### PR TITLE
Feature/head-bob

### PR DESCRIPTION
**Pull request by Royd54**
To test this feature, start the game and create a lobby. After loading into the map walk around and the screen should shake. The headbob types that are included are: Walk, Sprint, Jump, Crouch and Idle. The idle headbob starts after a couple of seconds when the player is standing still.

### CODE REVIEW

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
In `CargoChaos/Content/Blueprints/Characters/BP_Monster.uasset` under the `SRV_LandSound` event. The `Player` parameter isn't linked, this causes some nullpointer issues.

**Review by Stanley-Dam — COMMENTED** [review]
In `CargoChaos/Content/Blueprints/Characters/BP_Monster.uasset` under the `MC_LandSound` event. You're dividing the volume by a magic value. I recommend doing the division outside the function.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
In `CargoChaos/Content/Blueprints/Characters/BP_Player.uasset` under the `SRV_LandSound` event. You don't have to send the location of the player, the receiving client already has that data.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
In `CargoChaos/Content/HeadBob/Blueprints/BP_MonsterHeadBob.uasset` under the `SwitchStates` event. You're switching too early, all the states should do the same thing if true, I recommend using a sequence here and first execute the if statement and then execute the switch stuff.

**Review by Stanley-Dam — COMMENTED** [review]
In `CargoChaos/Content/HeadBob/Blueprints/BP_PlayerHeadBob.uasset` under the `SwitchStates` event. Same issue here as in the monster's headbob

**Review by Stanley-Dam — COMMENTED** [review]
In `CargoChaos/Content/HeadBob/Blueprints/BP_PlayerHeadBob.uasset`: `StartIdleTimer`, `OwningPlayer` and `As Character` can and should be private

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/HeadBob/Sounds/SoundCues/PlayerSighSound.uasset` can be removed since it won't be used.

**Review by Stanley-Dam — COMMENTED** [review]
`CargoChaos/Content/HeadBob/Sounds/SoundWaves/PlayerBreathing.uasset` also won't be used.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/HeadBob/Sounds/SoundWaves/PlayerSigh2.uasset` won't be used.

**Comment by Royd54** [comment]
> In `CargoChaos/Content/Blueprints/Characters/BP_Monster.uasset` under the `MC_LandSound` event. You're dividing the volume by a magic value. I recommend doing the division outside the function.

Changed magic value to variable. I decided to keep the division inside the function, because this division's function is there to assign the volume value for the owning client only. If the division takes place before the function this can't be achieved.

**Comment by Royd54** [comment]
> In `CargoChaos/Content/Blueprints/Characters/BP_Player.uasset` under the `SRV_LandSound` event. You don't have to send the location of the player, the receiving client already has that data.

Removed location parameter and used the location from the player parameter.

**Comment by Royd54** [comment]
> In `CargoChaos/Content/HeadBob/Blueprints/BP_PlayerHeadBob.uasset`: `StartIdleTimer`, `OwningPlayer` and `As Character` can and should be private

Made variables private.

**Comment by Royd54** [comment]
> `CargoChaos/Content/HeadBob/Sounds/SoundCues/PlayerSighSound.uasset` can be removed since it won't be used.

Removed all unused sounds.

**Pull request merged**
