### PR TITLE
Feature/evacuatie

### PR DESCRIPTION
**Pull request by TimoBrandt1**
Creating pull request for merging evacuate feature into develop branch.

### CODE REVIEW

**Comment by Royd54** [comment]
CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset class contains a custom event named CaptainEvacuate. Consider changing this to SRV_CaptainEvacuate to keep up the consistency with naming the events. This helps confusion with custom events that do not play on server side.

**Comment by Royd54** [comment]
CargoChaos/Content/Blueprints/Characters/BP_Player.uasset class contains a custom event named PlayerEvacuate. Consider changing this to SRV_PlayerEvacuate to keep up the consistency with naming the events. This helps confusion with custom events that do not play on server side.

**Comment by Royd54** [comment]
CargoChaos/Content/Evacuation/BP_Helikopter.uasset contains print strings that can be deleted. The class also contains a couple of custom events that might require a name change. MoveTowardsShip -> MC_MoveTowardsShip and MoveTowardsShipSRV -> SRV_MoveTowardsShip

**Review by Royd54 — CHANGES_REQUESTED** [review]
Rquested changes:
https://github.com/SuperEpicTeam/CargoChaos/pull/4#issuecomment-1092577573

https://github.com/SuperEpicTeam/CargoChaos/pull/4#issuecomment-1092579015

https://github.com/SuperEpicTeam/CargoChaos/pull/4#issuecomment-1092586226

https://github.com/SuperEpicTeam/CargoChaos/pull/4#issuecomment-1092591322

**Comment by TimoBrandt1** [comment]
Changed the custom event names within BP_Player and BP_Captain to SRV_'custom event name'. Also deleted an unnecessary print string within the BP_Helikopter blueprint. Lastly deleted the BP_EvacuationHelikopter actor, because it was no longer used.

**Review by Royd54 — APPROVED** [review]

**Pull request merged**
