### PR TITLE
Feature/tutorial

### PR DESCRIPTION
**Pull request by Stanley-Dam**
Added a tutorial level.
The tutorial can only be played via the tutorial level `/Content/Maps/Tutorial`.

### CODE REVIEW

**Comment by Royd54** [comment]
The player can collide with the invisible tasks. This can cause confusion etc. Maybe disable the collisions when they are invisible and enable them van the task gets revealed.

**Comment by Royd54** [comment]
I don't see any mayor issues. You made the tutorial blueprints readable even though tutorial blueprints don't look the prettiest normally.

**Comment by Stanley-Dam** [comment]
> 

I have previously decided not to do this since it will take some time to connect all the collision related nodes and it did not cause any issues in the playtests. The tutorial always went quite smoothly in that regard. I could do it, but I doubt if it would be worth our time (right now). :)

**Comment by Royd54** [comment]
> > 
> 
> I have previously decided not to do this since it will take some time to connect all the collision related nodes and it did not cause any issues in the playtests. The tutorial always went quite smoothly in that regard. I could do it, but I doubt if it would be worth our time (right now). :)

Maybe it is not the right time to implement it, but we should consider implementing this when we have the time. You can see in the playtests video's that people were bumping into them. So it would be a great overal game quality upgrade in my opninion.

**Comment by TimoBrandt1** [comment]
Everything seems fine to me too. The only thing that should be changed later on is that you can't die of the electrical task.

**Pull request merged**
