### PR TITLE
Feature/microphone task

### PR DESCRIPTION
**Pull request by Stanley-Dam**
Feature can be tested by walking up to the task an interacting with it using the 'E' button. The task explains itself after interacting.
The tasks requires you to interact with the 2 microphones on 2 different clients.

### CODE REVIEW

**Comment by Royd54** [comment]
CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset
I am getting some errors when testing (these errors consist of voice chat component errors and nul refs): 
image

**Comment by Royd54** [comment]
CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset

Maybe notify the player of the fact that they can't change the channel on the locked microphone actor (It took a while before I noticed).

**Comment by TimoBrandt1** [comment]
CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset - UpdateNoiceVolume
You have got a magic value after the -1 x.
image

**Comment by Royd54** [comment]
CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset

The frequency variable can be private?

**Comment by TimoBrandt1** [comment]
In CargoChaos/Content/Tasks/MicrophoneTask/Widgets/WBP_MicrophoneFrequencyInterface.uasset
Please comment some parts of the calculations in the code to make it more instantly readable. This is not nessesairy but it would be an improvement. 🐱‍👓
image

**Comment by Royd54** [comment]
CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset

The static noise did not get less static for the non channel locked microphone.

**Comment by Royd54** [comment]
CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset

Suggest making a var from the value 5 in the SetLockedChannel function. (This is the max int value in the random integer node)

**Review by Royd54 — CHANGES_REQUESTED** [review]
Cool stuff!! Some little things to check, but really clean overall. 👨‍💻👨‍🔬

**Comment by Stanley-Dam** [comment]
> CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset I am getting some errors when testing (these errors consist of voice chat component errors and nul refs): image

I was testing in standalone mode, so these errors didn't come up for me. Resolved all of them, thanks for this comment :)

**Comment by Stanley-Dam** [comment]
> CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset
> 
> Maybe notify the player of the fact that they can't change the channel on the locked microphone actor (It took a while before I noticed).

Good one, added a warning text to the locked microphone that tells the player that their microphone is locked.

**Comment by Stanley-Dam** [comment]
> 

-1 in specific is not a magic value, since it is simply the inverse of the given float. But I agree that * -1 + 1 is magic, added a comment that explains this calculation.

**Comment by Stanley-Dam** [comment]
> CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset
> 
> The frequency variable can be private?

It can't sadly, some functions use the frequency of the other microphone.

**Comment by Stanley-Dam** [comment]
> In CargoChaos/Content/Tasks/MicrophoneTask/Widgets/WBP_MicrophoneFrequencyInterface.uasset Please comment some parts of the calculations in the code to make it more instantly readable. This is not nessesairy but it would be an improvement. 🐱‍👓 image

I agree, I've added some comments.

**Comment by Stanley-Dam** [comment]
> 

I'm unable to recreate this bug, it could have something to do with the frequency move packets being unreliable. This should not cause any problems during actual gameplay since the frequency will be moved a lot and most of the packets will actually be registered.

**Comment by Stanley-Dam** [comment]
> CargoChaos/Content/Tasks/MicrophoneTask/Blueprints/BP_MicrophoneTask.uasset
> 
> Suggest making a var from the value 5 in the SetLockedChannel function. (This is the max int value in the random integer node)

Lol, already had a channel count variable, but I didn't use it there. Thanks for the comment :)

**Comment by Royd54** [comment]
> > 
> 
> I'm unable to recreate this bug, it could have something to do with the frequency move packets being unreliable. This should not cause any problems during actual gameplay since the frequency will be moved a lot and most of the packets will actually be registered.

This does cause problems, because the bug is only present in the clients. The mechanic works fine for the server, but not for the clients. (Recreated is 10/10 times by moving the slider on client side and switching microphones after to validate)

**Pull request merged**
