### PR TITLE
Feature/host system

### PR DESCRIPTION
**Pull request by Royd54**
This pull request contains the following features: Lobby creation/hosting, joining the created lobbies, assigning roles. This can be tested by hosting or joining a game trough the main menu. After connecting/creating a lobby the roles can be tested by filling the lobby to the required playercount. If the playercount is met the roles get assigned to the players. This is visual thanks to the lobby widget. This class puts the players under the correct tabs in the lobby menu. (Required playercount is shown in the top left of the lobby interface/ui)

### CODE REVIEW

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset`
MonsterWasSet & CaptainWasSet should be private and be in a category.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset`
Under the Select player to be a monster section there are loose notes.

**Review by Stanley-Dam — COMMENTED** [review]
`CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset`
In `SetHostGameSettings`, the comment block doesn't surround the logic.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset`
The `SetGameModeSettingsForDedicatedServer` function should be removed, we don't use dedicated servers.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset`
Hard coded magic value in the `CheckHostSettings` function, please explain why you are setting the `MinPlayerToStart` to 3, this should probably be a private readonly variable by the way.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GS.uasset`
The EverybodyReady variable should be private and have a category.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset` MonsterWasSet & CaptainWasSet should be private and be in a category.

Added a category and made variables private.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset` Under the Select player to be a monster section there are loose notes.

Deleted the loose nodes.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset` In `SetHostGameSettings`, the comment block doesn't surround the logic.

Extended the comment block.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset` The `SetGameModeSettingsForDedicatedServer` function should be removed, we don't use dedicated servers.

Removed obsolete function.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset` Hard coded magic value in the `CheckHostSettings` function, please explain why you are setting the `MinPlayerToStart` to 3, this should probably be a private readonly variable by the way.

Added explenation to the megic number. (The number sets the needed playercount back to the bare minimum aka hard reset). Did not change the variable to readonly however, because the value needs to be changable in the lobby settings menu.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GS.uasset` The EverybodyReady variable should be private and have a category.

Made the variable private and added a category.

**Pull request merged**
