### PR TITLE
Feature/fuse box

### PR DESCRIPTION
**Pull request by Royd54**
Feature can be tested by walking up to the task an interacting with it using the 'E' button. The task explains itself after interacting.

### CODE REVIEW

**Comment by TimoBrandt1** [comment]
I can't find any problems but some points that the blueprint CargoChaos/Content/Tasks/FuseBox/BP_Fusebox.uasset could still improve on is the readability of the code blocks at 'HandlePlayerInput'. If you would make more room for the code blocks on the different execution lines of the sequence it would become way more readable for me. Not a nessassairy change but a welcome one.🐱‍👤

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/Characters/BP_Player.uasset` in the event graph under the `InputAction Interact` and the `TaskInteractions` event. `TaskInteractions` on the server only gets called for the atena hoist, so the switch is redundant, but I think it should be called from `Input Action` anyway somehow?

**Comment by Stanley-Dam** [comment]
> `CargoChaos/Content/Blueprints/Characters/BP_Player.uasset` in the event graph under the `InputAction Interact` and the `TaskInteractions` event. `TaskInteractions` on the server only gets called for the atena hoist, so the switch is redundant, but I think it should be called from `Input Action` anyway somehow?

Also, I think that `TaskInteractions` should be reliable, since it only gets called once in a while and it's quite important.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Tasks/FuseBox/BP_Fusebox.uasset` in the event graph, I recommend using a rep notify for the `FuseActivationOrder`, and let it call an event dispatcher instead of using delays. Because these delays could be too short and that would break the feature.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Characters/BP_Player.uasset` in the event graph under the `InputAction Interact` and the `TaskInteractions` event. `TaskInteractions` on the server only gets called for the atena hoist, so the switch is redundant, but I think it should be called from `Input Action` anyway somehow?

This is already being done. The antenna TaskInteraction is instant, so that is why it is calleld in InputAction Interact. The reason that the TaskInteraction event excists is for future task behaviours that need to be fired from the task class itself.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Tasks/FuseBox/BP_Fusebox.uasset` in the event graph, I recommend using a rep notify for the `FuseActivationOrder`, and let it call an event dispatcher instead of using delays. Because these delays could be too short and that would break the feature.

Removed a delay. Let one delay stay, because of the cast to the widget. The rep notify has no effect on this.

**Pull request merged**
