### PR TITLE
Feature/singleplayer UI based task

### PR DESCRIPTION
**Pull request by Stanley-Dam**
Added an electrical task where the player has to make the pointer stop while it's in the green zone by pressing space bar. The player will get shocked when they miss the green zone. You can exit the task by pressing E again.

### CODE REVIEW

**Comment by Royd54** [comment]
In CargoChaos/Content/Blueprints/Characters/BP_Player.uasset DisableInteraction could be cleaned up in my opninion. You check fot the task type and then disable the task interaction based on the task type. This could be improved by implementing the Exit Task function into the task base class. This way the task type check is not needed anymore and we don't need to repeat code.

**Comment by Royd54** [comment]
In CargoChaos/Content/Tasks/ElectricalTask/Blueprints/ElectricalTask.uasset there is a magic value in use in the HandleInput event (DoSelfDamage function that gets a float of 10 as parameter). Maybe make this a variable so that the class gets an upgrade to the reusability/tweakabilty.

**Comment by Royd54** [comment]
In CargoChaos/Content/Tasks/ElectricalTask/Blueprints/ElectricalTask.uasset there is a variable called: CameraLerpAlpha. This variable can be private.

**Comment by Royd54** [comment]
CargoChaos/Content/Tasks/ElectricalTask/Widgets/ElectricalMeterWidget.uasset is an example of a couple of classes with the wrong name convention. Try to keep up with the naming of the classes from the project, to prevent confusion. ElectricalMeterWidget could be changed to WBP_ElectricalMeter for example.

**Comment by Royd54** [comment]
I noticed that there is no "how to play" visible for the player. Maybe add some text in the task widget that tells the player how to interact with the task.

**Review by Royd54 — CHANGES_REQUESTED** [review]
Great work overall, super clean and reusable! 👯‍♂️

**Comment by Stanley-Dam** [comment]
> In CargoChaos/Content/Blueprints/Characters/BP_Player.uasset DisableInteraction could be cleaned up in my opninion. You check fot the task type and then disable the task interaction based on the task type. This could be improved by implementing the Exit Task function into the task base class. This way the task type check is not needed anymore and we don't need to repeat code.

Good one, made an ExitTask event in the base class and made the electrical task overwrite it. Also cleaned up the player class a little more.

**Comment by Stanley-Dam** [comment]
> In CargoChaos/Content/Tasks/ElectricalTask/Blueprints/ElectricalTask.uasset there is a magic value in use in the HandleInput event (DoSelfDamage function that gets a float of 10 as parameter). Maybe make this a variable so that the class gets an upgrade to the reusability/tweakabilty.

Added a `DamageAmountOnFail` variable instead of using a magic value.

**Pull request merged**
