### PR TITLE
Feature/hoist antenna

### PR DESCRIPTION
**Pull request by Royd54**
This branch is testable by loading up into a game (with 2 clients) and pressing the buttons at the same time (next to the antenna in the TestMap level). If the reset timer is too fast you can tinker with the settings that are availible on the antenna en button objects. Intended functionality: when both buttons are pressed, the antenna raises bit by bit until it is straight.

### CODE REVIEW

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
Folder structure in the `Tasks` folder is incorrect, it misses type specific folders.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
In `CargoChaos/Content/Tasks/HoistAntenna/BP_AntennaButton.uasset` both `CanPress` and `ButtonCooldownLength` should be private. `ButtonCooldownLength` should also be readonly.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Tasks/HoistAntenna/BP_HoistAntenna.uasset` has an empty function `OnRep_PlayersPushed` which should probably be removed.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
In `CargoChaos/Content/Tasks/HoistAntenna/BP_HoistAntenna.uasset`: `PlayersPushed`, `ResetHoistAntennaTimer` and `RotationState` should be private.

**Comment by Stanley-Dam** [comment]
Suggestion: Maybe add some sound effects for player feedback? Like raising sounds and button presses.

**Comment by Royd54** [comment]
> Folder structure in the `Tasks` folder is incorrect, it misses type specific folders.

Created extra folders

**Comment by Royd54** [comment]
> In `CargoChaos/Content/Tasks/HoistAntenna/BP_AntennaButton.uasset` both `CanPress` and `ButtonCooldownLength` should be private. `ButtonCooldownLength` should also be readonly.

Made the variables private. Also made `ButtonCooldownLength` readonly

**Comment by Royd54** [comment]
> `CargoChaos/Content/Tasks/HoistAntenna/BP_HoistAntenna.uasset` has an empty function `OnRep_PlayersPushed` which should probably be removed.

Deleted var rep notify function

**Comment by Royd54** [comment]
> In `CargoChaos/Content/Tasks/HoistAntenna/BP_HoistAntenna.uasset`: `PlayersPushed`, `ResetHoistAntennaTimer` and `RotationState` should be private.

Made the variables private.

**Comment by Royd54** [comment]
> In `CargoChaos/Content/Blueprints/Characters/BP_Player.uasset` you're setting a hard coded magic value as the Max Acceleration under the `InputAction Interact` event. This could later become an issue if we decide to tweak with the player speed some more for example.

Converted the magic value to a variable, so that it can be changed later down the line.

**Comment by Royd54** [comment]
> Suggestion: Maybe add some sound effects for player feedback? Like raising sounds and button presses.

Added player feedback thanks to some sounds.

**Pull request merged**
