### PR TITLE
Feature/player movement

### PR DESCRIPTION
**Pull request by Royd54**
This feature can be tested by hosting a lobby and connecting to the created lobby with 4 windows/instances of the game. After connecting every players needs to ready up, so the game can start. After the game started every player should get a notification in their screen. This notification contains their given player role. This role can also be seen in the bottom left of the game window. 

The movement can be tested by walking with WASD, jumping with SPACE and crouching with CTRL. Note that the pirate can't crouch!

### CODE REVIEW

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/Actors/BP_SafeZoneForPlayers.uasset`
In the `begin overlap` you check if the name corresponds, don't do that. Instead use a cast.

**Review by Stanley-Dam — COMMENTED** [review]
`CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset`
Please check if the accessibility of the variables are right. None of them are private.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset`
Hardcoded magic values under the beginplay.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset`
The player role text under the Beginplay is in dutch.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/Characters/BP_Monster.uasset`
The `GetPlayerRoleText` is completely unnecessary, it can't be anything else than the pirate.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/Characters/BP_Player.uasset`
Same here, `GetPlayerRoleText` is unnecessary.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/HideAndSeek/BP_MainGI.uasset`
Loose print note under the Destroy session section.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Blueprints/Widgets/Game/WBP_HUD.uasset`
`BindGetPlayerRole` returns roles in dutch.

**Review by Stanley-Dam — COMMENTED** [review]
`CargoChaos/Content/Evacuation/BP_Helikopter.uasset`
Class name is dutch, should be Helicopter

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Evacuation/BP_Helikopter.uasset`
Begin overlap has duplicate code of Gate? I think the gate stuff should be removed.
It also has the same problem where you're checking the display name instead of a cast?

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
`CargoChaos/Content/Evacuation/BP_Helikopter.uasset`
Hard coded magic values in BeginPlay

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Actors/BP_SafeZoneForPlayers.uasset` In the `begin overlap` you check if the name corresponds, don't do that. Instead use a cast.

Changed this to casts. Note that I did not make this class, so next time assign correct person to the requested changes. This way there is no chance we break each others classes/functionality...

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset` Please check if the accessibility of the variables are right. None of them are private.

Checked accessibility and changed them accordingly.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Characters/BP_Monster.uasset` The `GetPlayerRoleText` is completely unnecessary, it can't be anything else than the pirate.

Deleted unnecessary function and made the notification a hardcoded string, because it does not need to be reused.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset` Hardcoded magic values under the beginplay.

Removed values, because they don't need to be overriden anymore. (the values were inherited from BP_Player)

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset` The player role text under the Beginplay is in dutch.

The text is in dutch, because that is the language that needs to be used according to the client. Changed the text to english anyway, because I don't think this is the correct place to discuss this.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Characters/BP_Player.uasset` Same here, `GetPlayerRoleText` is unnecessary.

This isn't true. The GetPlayerRoleText function gets inhereted by other classes/playertypes. (BP_Captain and BP_Mole). This way we  don't need to make the same functionality over and over again.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/HideAndSeek/BP_MainGI.uasset` Loose print note under the Destroy session section.

Connected the debug node

**Comment by Royd54** [comment]
> `CargoChaos/Content/Blueprints/Widgets/Game/WBP_HUD.uasset` `BindGetPlayerRole` returns roles in dutch.

The roles are in dutch, because that is the language that needs to be used according to the client. Changed the roles to english anyway, because I don't think this is the correct place to discuss this.

**Comment by Royd54** [comment]
> `CargoChaos/Content/Evacuation/BP_Helikopter.uasset` Class name is dutch, should be Helicopter

Changed the class name. Note that I did not make this class, so next time assign correct person to the requested changes. This way there is no chance we break each others classes/functionality...

**Comment by Royd54** [comment]
> `CargoChaos/Content/Evacuation/BP_Helikopter.uasset` Begin overlap has duplicate code of Gate? I think the gate stuff should be removed. It also has the same problem where you're checking the display name instead of a cast?

Changed this to casts. Note that I did not make this class, so next time assign correct person to the requested changes. This way there is no chance we break each others classes/functionality...

**Pull request merged**
