### PR TITLE
Feature/captain hat

### PR DESCRIPTION
**Pull request by TimoBrandt1**
Pull request for captain hat.

### CODE REVIEW

**Comment by Royd54** [comment]
Pirate hat is still visible if you play another match.
image

**Comment by Royd54** [comment]
Other stuff seems fine to me, good job my guy! 🐱‍💻

**Review by Stanley-Dam — COMMENTED** [review]
In `CargoChaos/Content/Blueprints/Characters/BP_Captain.uasset` in the `EventGraph` -> `Event IE Destroy Self`, you should check if the captain hat is valid, I got an error after picking it up before the 5 second delay had ended.

**Review by Stanley-Dam — COMMENTED** [review]
Couldn't find anything else, good work :)

**Comment by TimoBrandt1** [comment]
Both of the requested changed implemented and also fixed a bug were the crewmates would still drop the captain hat.

**Comment by Royd54** [comment]
> Pirate hat is still visible if you play another match. image

This bug is still present for me. Maybe try to delete all the hats when the players go to the lobby?

**Pull request merged**
