### PR TITLE
Feature/win lose conditions

### PR DESCRIPTION
**Pull request by TimoBrandt1**
I hope everything is perfectly made! If not you can leave your feedback down below.

### CODE REVIEW

**Review by Stanley-Dam — COMMENTED** [review]
In `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GM.uasset`
under the `ProcessPlayerEvacuation` function. The sequence is unnecessary, you only have to check the player counter & captain state if the escaping player is not the captain :)

Removing the sequence will make the function a little more compact & readable, it's not a big issue performance wise.

**Review by Stanley-Dam — COMMENTED** [review]
In `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GS.uasset` under the `GetWinner` function. You have a hard coded magic value for the amount of generators that have to be fixed. Please change this to a readonly private variable so it can easily be changed in the future.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
In `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GS.uasset` under the `GetWinner` function. The `Then 3 & 4` will never be executed, since you always return something in pin 2. Maybe change the sequence order?

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
In `CargoChaos/Content/Evacuation/BP_Helicopter.uasset` under the `BeginOverlap`. You are doing a lot of double work by checking if the game should end. The Player & Captain evacuate functions already do this.

**Review by Stanley-Dam — COMMENTED** [review]
In `CargoChaos/Content/Evacuation/BP_Helicopter.uasset` under the `DropEvacuationRope` event. You are using a hard coded magic value for the B value of the lerp. You could maybe use a raycast (raytrace) to determine the rope length?

**Comment by TimoBrandt1** [comment]
Hello Stanley! Thanks for this epic review. I have changed the blueprint that you requested :). I hope you are satisfied with my work. Best Regards Timo.

**Comment by Stanley-Dam** [comment]
In `CargoChaos/Content/Evacuation/BP_Helicopter.uasset` under the `DropEvacuationRope` event. This does not work, you devide the length of the raytrace by 4, which is the same hard code but more scuffed.

**Comment by Stanley-Dam** [comment]
> In `CargoChaos/Content/Blueprints/HideAndSeek/BP_HideAndSeek_GS.uasset` under the `GetWinner` function. You have a hard coded magic value for the amount of generators that have to be fixed. Please change this to a readonly private variable so it can easily be changed in the future.

The `RequiredRepairedGenerators` should not be replicated and it should be readonly.

**Review by Stanley-Dam — CHANGES_REQUESTED** [review]
Unused code in Helicopter blueprint

**Pull request merged**
